# Generated by Django 3.0.7 on 2021-02-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='google_plus',
            new_name='google_link',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='twitter',
            new_name='twitter_link',
        ),
    ]
